const fs = require("fs");

const CONTENTS = {
  MICRO: {},
  MINI: {},
  SOLID: {},
  OUTLINE: {},
  HEAD: {},
  TAIL: "",
};

const subDirs = [["16/solid", "MICRO"], ["20/solid", "MINI"], ["24/outline", "OUTLINE"], ["24/solid", "SOLID"]];

subDirs.forEach((subDir) => {
  const [dirPath, style] = subDir;
  const path = `./node_modules/heroicons/${dirPath}/`;
  const fileNames = fs.readdirSync(path);

  const object = CONTENTS[style];

  fileNames.forEach((filename) => {
    const contents = fs
      .readFileSync(path + filename)
      .toString()
      .trimEnd();
    const lines = contents.split("\n");
    if (!CONTENTS.HEAD[style]) {
      CONTENTS.HEAD[style] = lines[0].replace(/ aria-hidden="true"/g, "");
    }
    if (!CONTENTS.TAIL) {
      CONTENTS.TAIL = lines[lines.length - 1];
    }
    const guts = lines
      .slice(1, lines.length - 1)
      .join("")
      .replace(/\ \ /g, "");
    object[filename.slice(0, -4)] = guts;
  });
});

fs.writeFileSync(
  "./icons.js",
  `// This file was generated by build.js at ${new Date().toISOString()}\n\nmodule.exports = ${JSON.stringify(
    CONTENTS
  )};\n`
);
